### ISSUE TITLE
World-low svg problem

### ISSUE THREAD

**Issue by pgnsamu** [GrandSir/InteractiveMap#1]
with the "world-low" map the us land is a bit shifted to the right 
![Simulator Screen Shot - iPhone 11 - 2022-10-03 at 20 58 14](https://user-images.githubusercontent.com/76209569/193656925-c82c9460-3f48-49c9-81a2-f07263b242a3.png)

**Comment by grandsir** [comment]
Thanks for submitting this issue, will fix it soon 👍

**Comment by grandsir** [comment]
Hey @pgnsamu, it took quite long for me to figure out where I was wrong and I noticed that I was handling horizontal and vertical lines wrong, and I fixed it, now you can use it normally.

Sorry for this issue, have a good day.
<img width="1680" alt="Screen Shot 2022-10-17 at 14 45 12" src="https://user-images.githubusercontent.com/69051988/196168980-0692d55a-2c94-48be-a6a4-0e00efbf6e5b.png">

**Comment by grandsir** [comment]
Also, use .stroke(0.4) or something like that for big maps
