### ISSUE TITLE
Shape üzerinde şehir isimleri

### ISSUE THREAD

**Issue by Mert7126** [GrandSir/InteractiveMap#10]
Merhaba projeniz için teşekkür ederim. Burada sormak istediğim bir konu var ve mümkünse yardımı olmanızı rica ediyorum. Her bir şehrin üzerinde o şehirin ismini yazmasını istiyorum ancak kodun içinde pathData dan 

x = (pathData.boundingBox?.origin.x ?? 0)
y = (pathData.boundingBox?.origin.y ?? 0)

bu şekilde coordinatları alıyorum şehrin tam ortasında göstermiyor bunu nasıl yapabilirim?

     InteractiveMap(svgName: "tr") { pathData in
                        InteractiveShape(pathData)
                            .initWithAttributes()
                            .overlay(content: {
                                
                                ZStack(alignment: .center) {
                                    
                                    Text("\(pathData.id)")
                                        .font(.system(size: 10))
                                    
                                }
                                .position(x: pathData.boundingBox?.origin.x ?? 0, y: pathData.boundingBox?.origin.y ?? 0)
                           
                            })
                        
                            .shadow(color: clickedPath == pathData ? Color("app_white") : .clear, radius: 2)

                            }
                            .scaleEffect(clickedPath == pathData ? 1.02 : 1)
                            .animation(.easeInOut(duration: 0.2), value: clickedPath)
                            .zIndex(clickedPath == pathData ? 2 : 1)
                        
                    }

**Comment by grandsir** [comment]
Oluşturduğunuz Issue için teşekkür ederim, şu anda sorununuzu incelemekteyim. Fakat issue'yı kapatacağım ve ingilizce açmanızı rica edeceğim ki başka insanlar da baktıklarında anlayabilsinler, teşekkürler.
