### ISSUE TITLE
InteractiveMap Error: File Not Found.

### ISSUE THREAD

**Issue by daggewo** [GrandSir/InteractiveMap#3]
Hi there, 

I would just love to play around with this but can't get it to work (beginner).

I get the error:
InteractiveMap Error: File Not Found.

Even though I have added the package and copy/pasted the code. Do you have an idea of what might be wrong?

Kind regards,
Dag
<img width="1792" alt="Skärmavbild 2023-07-27 kl  10 50 26" src="https://github.com/grandsir/InteractiveMap/assets/96787288/6c6ee13f-2778-4643-8779-7a2565743f19">

**Comment by grandsir** [comment]
Hey there.

The issue is simple, The interactive map package looks for an SVG called "tr.svg" in your main bundle, but there's no such thing like that so it returns an error.

In the example project, I simply create a folder called **maps** and just drag and drop my maps to there.

**Comment by daggewo** [comment]
Thanks a lot grandsir, 

If you would be so kind to just assist me one step further :)

I just put in an svg-file with the Swedish municipalities but many of them are missing, do you have an idea what might be the problem? There are a total of 290 municipalities.

<img width="1792" alt="Skärmavbild 2023-07-28 kl  08 12 45" src="https://github.com/grandsir/InteractiveMap/assets/96787288/4226179d-2849-4c45-ae57-186bcc6ac145">

**Comment by grandsir** [comment]
Some of the svg files are not supported, as they have a very different kind of formatting, can you describe me your needs so i can find the best svg for you

**Comment by daggewo** [comment]
That's very kind of you. I want an app which shows all Swedish municipalities (290). Upon click it shows the name of the municipality. That's all :)
