### ISSUE TITLE
Any way to center a map on the available width?

### ISSUE THREAD

**Issue by Memocana** [GrandSir/InteractiveMap#6]
I'm using the map attached below, and no matter how I edit the file, it is always drawn to the left, not the center of the view. I also have the same issue with the UK map included in the Example Maps section.

Screenshots:
<img width="369" alt="Screenshot 2023-09-02 at 5 17 16 PM" src="https://github.com/grandsir/InteractiveMap/assets/7967331/43d85a50-8f6c-4232-827c-846337b5411a">
<img width="325" alt="image" src="https://github.com/grandsir/InteractiveMap/assets/7967331/71bd1c20-4681-4113-a535-84484075dd0a">

Images:
![AU-low](https://github.com/grandsir/InteractiveMap/assets/7967331/e801b35a-4d35-43b1-80c5-8645cf434283)
![GB-low](https://github.com/grandsir/InteractiveMap/assets/7967331/dfbc589d-d8b4-4f91-bdc4-d7857a06de0a)

**Comment by grandsir** [comment]
That's definitely a strange bug. Can you try adding this to the InteractiveMap(Not InteractiveShape)?

.frame(pathData.svgBounds)

and see if that fixes it.

**Comment by Memocana** [comment]
<img width="372" alt="image" src="https://github.com/grandsir/InteractiveMap/assets/7967331/467aeb6d-48bb-4e63-bb3d-e2e0f98398b6">

Unfortunately this time it extended beyond the bounds with that change. Also thank you for all your efforts and help on this great library!

**Comment by Memocana** [comment]
For reference I have the interactive map in a VStack, aligned centrally

**Comment by grandsir** [comment]
Thank you for detailed information, i'll take a look at it.

**Comment by Begoodi** [comment]
I put the MapView in a ZStack, and applied an offset to have the map at the right place.
Not a fix, but a workaround.

**Comment by grandsir** [comment]
I think the quickest solution is just adding 
```swift
    .frame(width: UIScreen.main.bounds.height, height: UIScreen.main.bounds.height)
```

This to the InteractiveMap.

**Comment by daggewo** [comment]
Hey Grandsir. The frame-modifier doesn't help either. Have you looked into any more, how to get the maps to centralise in its view? Thanks in advance.
/Dag

**Comment by grandsir** [comment]
I'll check it again, thanks @daggewo
